export { default as PROFILE } from '../assets/imgs/profile.webp';
export { default as BURGER_LARGE_CHEESE } from '../assets/imgs/burger_large_cheese.webp';
export { default as BURGER_LARGE_CHICKEN } from '../assets/imgs/burger_large_chicken.webp';
export { default as BURGER_ORIGIN } from '../assets/imgs/burger_origin.webp';
export { default as CHICKEN_BBQ } from '../assets/imgs/chicken_bbq.webp';
export { default as FRENCH_FRIES } from '../assets/imgs/french_fries.webp';
export { default as NUGGET } from '../assets/imgs/nugget.webp';
export { default as CHICKEN_CHUNKS } from '../assets/imgs/chicken_chunks.webp';
export { default as VEGAN_BURRITO } from '../assets/imgs/vegan_burrito.webp';