export { default as PROFILE } from '../assets/imgs/profile.png';
export { default as BURGER_LARGE_CHEESE } from '../assets/imgs/burger_large_cheese.png';
export { default as BURGER_LARGE_CHICKEN } from '../assets/imgs/burger_large_chicken.png';
export { default as BURGER_ORIGIN } from '../assets/imgs/burger_origin.png';
export { default as CHICKEN_BBQ } from '../assets/imgs/chicken_bbq.png';
export { default as FRENCH_FRIES } from '../assets/imgs/french_fries.png';
export { default as NUGGET } from '../assets/imgs/nugget.png';
export { default as CHICKEN_CHUNKS } from '../assets/imgs/chicken_chunks.png';
export { default as VEGAN_BURRITO } from '../assets/imgs/vegan_burrito.png';